### ISSUE TITLE
guidance

### ISSUE THREAD

**Issue by t-51** [M03ED/Marzban_Bulk_Account_Maker#1]
Hello good time
You said that instead of the API that you used, put the real API of the server, so where is this thing you are saying and how can we find it?

**Comment by M03ED** [comment]
just put your real domain and port in this variable  

API_URL = 'https://Domain.com:port/api'

**Comment by t-51** [comment]
Enter the server terminal?

**Comment by t-51** [comment]
Dear friend, you wrote this script, but I'm sure no one has been able to use it!
Please make a tutorial so that we know how it works

**Comment by M03ED** [comment]
for using this script you just need a simple knowledge about how to run code with vs code , nothing more

**Comment by t-51** [comment]
Well, dear, the problem is that a professional user does not need this script, it is made for people who do not have enough knowledge

**Comment by M03ED** [comment]
when you come and use marzban for sell you should learn these things , your not a regular user anymore 
and this script is for sellers

**Comment by t-51** [comment]
Dear, I am not a regular user and I am a seller and I know this is a Python script.
But the problem is that you took pains to write and make it available to the public, but no one knows, even the developers, we asked, they said that we do not know how to work with this script that you wrote.
You didn't announce either the order of execution, the route of execution, or the method of execution!
Again, I emphasize that a programmer does not need your script, he can make it himself. The person who needs it is an experienced and new user to be able to do his own work.
